### ISSUE TITLE
Problem after upgrading ko to 3.5.1

### ISSUE THREAD

**Issue by pablolmedorado** [rniemeyer/knockout-sortable#203] opened 2019-11-07 15:26 UTC
First of all, I'd like to thank you for such an useful library.

I think I've found an error after upgrading knockout version to 3.5.1

As far as I know, the "object" binding format doesn't work. If you use the observableArray as the binding value, it works as always.

I've created a jsfiddle with the error: https://jsfiddle.net/6w74czhp/5/

I've tested the example with both 1.1.1 and 2.0.0 versions of your library with the same result. It works with 3.5.0 but not with 3.5.1.

Thanks in advance.

**Comment by fastfasterfastest** [comment] 2019-11-07 17:42
Probably duplicate of https://github.com/rniemeyer/knockout-sortable/issues/199

**Comment by rniemeyer** [comment] 2019-11-07 20:55
Version 1.2.0 is out there that includes a fix for this issue. Updated fiddle: https://jsfiddle.net/n1egw98b/

Thanks!

**Closed by rniemeyer** 2019-11-07 20:55 UTC

**Comment by pablolmedorado** [comment] 2019-11-08 06:44
Amazing response time! Thank you so much!
